### PR TITLE
Generic cluster umut

### PR DESCRIPTION
**Pull request by usirin**
# Description

Refactor and rebuild the component & types.

**discord username: `umut#3072`**

### CODE REVIEW

**Comment by eraygundogmus** [comment]
deploy failed

**Review by eraygundogmus — CHANGES_REQUESTED** [review]
possible build error

**Comment by usirin** [comment]
TODO: pass radius as props to GenericClusterGroup
TODO: update filter route.push to include all filters
TODO: update URL on first load with default filters
TODO: Nearby markers
TODO: onCopyClipboard (copy map link)
TODO: Previously Clicked marker needs to be gray
TODO: swap lat&lng in heatmap

cc @oguzergul @fdemir @mertkaya1033

**Comment by oguzergul** [comment]
I fixed copy clipboard, heatmap, and radius prop.  todos. I still work on saving visited markers on local forage. @usirin @fdemir

**Comment by usirin** [comment]
- [ ] TODO: move drawer open - close handlers to a common place

**Comment by mertkaya1033** [comment]
I am working on moving things to getServerSideProps and updating filter route.push to include all filters @oguzergul @fdemir

**Pull request merged**
