### PR TITLE
Add Arabic localization and some fixes

### PR DESCRIPTION
**Pull request by abdurrahmanseyidoglu**
# Description
- Add Arabic language
- Fix "tags" key in the English translation
- Add .yarn to .gitignore

**discord username: Mr XQ#3590**

*Adding Feature**

## Things to check before creating a PR
- [x] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with an approved tag. Otherwise PR will be rejected. 
It's not an issue but extending a feature #localization
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [x] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [x] Related file selection: Only relevant files should be touched and no other files should be affected.
- [x] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [x] Clean commit history: The commits where the changes are made should be clear and organized.
- [x] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [x] A new feature (a change that adds a new feature, not a breaking change)
- [x] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by DavutDurgun — APPROVED** [review]

**Comment by eraygundogmus** [comment]
please remove lock file from this pr

**Review by eraygundogmus — CHANGES_REQUESTED** [review]
don't touch anything else except PR title

**Comment by eraygundogmus** [comment]
I am closing this pr because there is no any issue related.

**Comment by abdurrahmanseyidoglu** [comment]
@eraygundogmus  Is the PR closed due to yarn.lock file and commit message or due to not having an issue related to the PL ?

**Pull request closed without merging**
