### PR TITLE
fix: channel names on feed content

### LINKED ISSUE #1166: Feat: user friendly channel names
## Define your request
We'd better to have users friendly channel names to show within the left drawer. 

With the new filter categorization, user filters a category and then clicks on a marker. When the left drawers opens,  user may have a confusing channel name. To not confuse the user, we need user friendly channel names. 

For example, When user filters the `enkaz`, the channel name may have `Teyit_enkaz`.  It would be great to have Teyitli Enkaz Verisi or Enkaz (Teyitli) for the Turkish language options. 

> -- fill in the line below:
** discord username: @sercanerhan#0543 **

image

### PR DESCRIPTION
**Pull request by oguzergul**
# Description

**discord username: afetharita#0001**

**closes #1166 **

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by eraygundogmus — CHANGES_REQUESTED** [review]
Let's add this in locale files so we can support other languages

**Review by eraygundogmus — APPROVED** [review]
since my comment related other issue, i am approving this issue

**Comment by sercanerhan** [comment]
@oguzergul  can't verified this on https://github.com/acikkaynak/deprem-yardim-frontend/pull/1173 with this [url](https://deprem-yardim-frontend-hkh9qlcms-afet.vercel.app/en?lat=36.20290447984869&lng=36.075668334960945&zoom=12&reasons=enkaz&id=1601270)
image

**Comment by oguzergul** [comment]
generic feed content component takes multiple channels. i will map them all.

**Comment by eraygundogmus** [comment]
@oguzergul should I merge this_?

**Pull request merged**
