### PR TITLE
(feat: #663): keep marker click history and grayscale previously clicked markers

### LINKED ISSUE #663: feat: changing the color of previously clicked pinpoints
While the data validation team is validating the data on aferharita;
Veri Kontrol Ekibi afetharita üzerinden verileri kontrol ederken; 
- Adding new data to system,
- The loose of pinpoints by the validator, 
- In backward validations

In this situations like this, there is an interfere which pin to look at. That situation slows down the control process.

discord username: @muammerakca10#2783

I think it will speed up the control process changing the clicked pin color interferes with the heatmap colors

### PR DESCRIPTION
**Pull request by patateskafa**
# Description

Render previously clicked markers grey by keeping the marker click history at the client side using [localForage](https://github.com/localForage/localForage) as described in the issue comments.

**discord username: AlpA#6691**

**closes #issue**
https://github.com/acikkaynak/deprem-yardim-frontend/issues/663

image

### CODE REVIEW

**Comment by fdemir** [comment]
what is the relevant issue for this task? product approved label needed.

**Comment by patateskafa** [comment]
the relevant issue is https://github.com/acikkaynak/deprem-yardim-frontend/issues/663

**Review by fdemir — APPROVED** [review]

**Comment by fdemir** [comment]
needs to be tested before merge.

**Review by fdemir — APPROVED** [review]

**Review by OrhanOzkercin — APPROVED** [review]
lgtm

**Comment by sevilayerkan** [comment]
@fdemir  Tested on PR branch.
Result : The markers returns to grey when clicked upon by adding ids local storage

Tested on : https://deprem-yardim-frontend-git-fork-patateskafa-development-afet.vercel.app/en?lat=38.54166625595791&lng=38.0884516618627&zoom=11.75&id=808805
Browser : Chrome (Web), Safari (Mobile)

image

**Pull request merged**
