### PR TITLE
fix(#729): options sizes adjusted for mobile

### PR DESCRIPTION
**Pull request by absolutezero13**
# Description
Options section reported as too big for mobile screens, I tried make it a bit more responsive. I will put a SS down below, it might be a little more smaller if requested.

**discord username: İlker Sarica#7138**

**closes #issue**: #729 

Screenshot 2023-02-11 at 08 54 50

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by cdagli** [comment]
I added the UX/UI label, let's get a review from them.

**Comment by oguzergul** [comment]
@handekaratas96 @absolutezero13  we need to take feedback for this. We need to learn if option sizes are accessible for mobile and also we are open to other feedback.

**Comment by berkaydesign** [comment]
I don't know what is options, couldn't understand. Could you tell me a bit more about it? @absolutezero13

**Comment by cdagli** [comment]
There has been some updates in the Figma which impacts this one as well: https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afetharita.com?node-id=2349%3A8093&t=f6awKxgk9198heIf-0 Please have a look. But I think it is still work in progress. 

Once the first iteration is finalised, we can continue with this PR.

**Comment by fdemir** [comment]
what is the related issue for this task?

**Comment by absolutezero13** [comment]
> There has been some updates in the Figma which impacts this one as well: https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afetharita.com?node-id=2349%3A8093&t=f6awKxgk9198heIf-0 Please have a look. But I think it is still work in progress.
> 
> Once the first iteration is finalised, we can continue with this PR.

is it finalised? where should I ask? will continue accordingly

**Comment by berkaydesign** [comment]
you can ask to me @absolutezero13 , I am leading the afetharita.com's design team. you can tag me on frontend text channel on discord

**Pull request closed without merging**
