### PR TITLE
fix(#840): display the records with the same address

### LINKED ISSUE #840: bug: there is no way to see the details of the points with the same locations
## Bug Definition

As you can see, there are 10 points returned from the backend, but only 2 are displayed on the map. Points with the exact same location are not clustered and are shown as a single point.

SCR-20230212-mv5

-- Please add discord contact information
** discord username: @el#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

2. Click '....' 
3. Scroll to '....' 
4. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

### PR DESCRIPTION
**Pull request by el**
# Description

SCR-20230212-pkx

**discord username: afetharita#0001**

**closes #840 **

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by Rayberk — CHANGES_REQUESTED** [review]
It opens when you click twice or reopen the drawer

**Comment by oguzergul** [comment]
preview is failed, I can not test it. but maybe we can add a gap between badges for accessibility.

**Comment by el** [comment]
@oguzergul Ekledim 👍 
SCR-20230212-q5n

**Review by Rayberk — COMMENTED** [review]
The drawer opens with only 1 click and other locations show up
The gaps are fine

**Review by Rayberk — COMMENTED** [review]
gaps & click works fine

**Review by Rayberk — DISMISSED** [review]

**Comment by fdemir** [comment]
same location part could be bold or italic.

**Comment by el** [comment]
@fdemir can you please approve the pr?

**Review by oguzergul — DISMISSED** [review]

**Comment by dopplerDistortion** [comment]
@el seems like something wrong with localisations

**Review by Rayberk — DISMISSED** [review]

**Review by nejatcanunlu — APPROVED** [review]

**Review by Rayberk — APPROVED** [review]

**Comment by el** [comment]
@dopplerDistortion That is an issue on the development branch, I fixed that too

**Review by oguzergul — APPROVED** [review]

**Review by nejatcanunlu — APPROVED** [review]

**Pull request merged**
