### PR TITLE
feat(#692): add reasoning filter menu and filter time state save to url

### LINKED ISSUE #692: bug: making notification selection persistent
## Bug Definition

The page resets when i change notification type and f5

** discord username: @ss.ibrahimbas#4990 **

## Bug environment
Web environment: rc.afetharita.com
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Click to 'Bildirimler/Notifications' dropdown
2. choose 'Erzak Yardımı / Vittles Support' option
3. F5
4. Data is resetted

## Expected Behaviour

My selection stay with me on page refresh
Sayfayı yenilediğimde tercihlerimin benimle kalması

## Screenshots
image

## Desktop Information
- Operating System : [Windows 11]
- Browser [chrome]
- Version[unknown]

### PR DESCRIPTION
**Pull request by naimyurek**
# Description

**discord username: naim#2823**

**closes #692 **

Data was written to the URL to ensure that
the selected dropdowns do not change when
the page is refreshed.
Sharing the URL will also ensure that
the same filters are shared.

## Things to check before creating a PR
- [x] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by serhhan — DISMISSED** [review]
It works as expected, approved.

**Comment by sevilayerkan** [comment]
As test team we retested this pr. Filters come as same after page refresh but url changes. 

In the test we seen this urls:
In first we saw : https://deprem-yardim-frontend-fjsey3gln-afet.vercel.app/?lat=37.809317853907494&lng=37.66281782105332&zoom=11.75&id=761985&reasoningFilter=erzak&timeFilterOption=last3Days 
After refresh : https://deprem-yardim-frontend-fjsey3gln-afet.vercel.app/?lat=37.809317853907494&lng=37.66281782105332&zoom=11.75  we saw this url but filters seems as before.

**Comment by cdagli** [comment]
@sevilayerkan Can you please update the labels if the tests are failed. Thank you.

**Comment by sevilayerkan** [comment]
We assumed this was an expected result if it's not then we are adding the `test-failed`

**Comment by oguzergul** [comment]
@naimyurek this pr has conflicts can you resolve this ?

**Comment by naimyurek** [comment]
The confilicts have been resolved but other changes have been reverted. Can you just look at the file changes without worrying about the commits in between?

**Comment by cdagli** [comment]
@naimyurek Unfortunately, the URL is getting changed when we pan in the map. Can you check if you can fix that as well?

**Comment by eraygundogmus** [comment]
we have urgent problems. please keep this work in your locale. we will announce when we need this features.

**Comment by naimyurek** [comment]
@eraygundogmus This problem is not caused by my changes. While zooming in and zooming out, my settings are deleted while the parameters are set. I looked, but that structure was a bit confusing.

**Comment by naimyurek** [comment]
> @naimyurek Unfortunately, the URL is getting changed when we pan in the map. Can you check if you can fix that as well?

i don't understand can you send the comments on discord

**Pull request closed without merging**
