### PR TITLE
feat: save filters to localstorage

### LINKED ISSUE #893: bug: Filters are not kept when user refreshes the page
## Bug Definition
Filters are not kept when user refreshes the page

-- Please add discord contact information
** discord username: @notDepresseDeveloper#0919 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to afetharita.com or rc.afetharita.com
2. Select something from filters
3. Refresh the page
4. Bug appears

## Expected Behaviour
Filters have to be cached and user should see previous filter they choose.

## Desktop Information
- Operating System: Windows 10, 11
- Browser: Chrome, Safari

## Mobile Phone Information
- Operating System (with the version): Android, IOS 
- Browser : Chrome, Safari (for IOS), Samsung Browser (Android)

### PR DESCRIPTION
**Pull request by ugurrdemirel**
# Description

**discord username: Uğur Demirel#7911**

**closes #893**

I add simple useLocalStorage hook to save filters and load it back when page is refreshed.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Changes

- [x] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

### CODE REVIEW

**Comment by puskuruk** [comment]
Instead of saving values to local storage separately we can use `persist` middleware from `zustand` to sync the store with localStorage.

**Comment by ugurrdemirel** [comment]
I'm not familiar with zustand actually, so I made these changes with localstorage. Feel free to close pr if it will mess up the structure 👍

**Comment by ssibrahimbas** [comment]
how logical is it to save filters to localStorage? Do I really need to see the same filter when I enter the site 2 days from now?

It makes more sense to keep it in the url instead.

**Comment by usirin** [comment]
agreed, this needs to be saved in url.

**Pull request closed without merging**
