### PR TITLE
feat(739): create api route for ahbap locations

### LINKED ISSUE #739: feat: Import ahbap google maps data and show it as another layer on map
## Define your request
We want to import the data ahbap uses in google maps from: https://www.google.com/maps/d/u/0/viewer?mid=1aQ0TJi4q_46XAZiSLggkbTjPzLGkTzQ&hl=tr&fbclid=PAAabyVDiTmFsFSPkcoAfAd9pcy5poekIm5LfUOndiuxmCXEMq4By3ObMr-_8&ll=0%2C0&z=6

**discord username: `umut#3072`**

Strategy
- [ ] Create an api route at next.js backend and fetch `kml`/`kmz` data for the above map.
  - [ ] Use an in-memory cache that invalidates itself every 5 minutes.
  - [ ] Serve the kml/kmz files from this in-memory cache so we will hit google maps every 5 mins (as opposed to hitting it with every request)

### PR DESCRIPTION
**Pull request by cansirin**
# Description
We want to render secure locations addresses coming from Ahbap Google Maps data. This PR creates an API route to fetch that data and serve as an endpoint.

**discord username: csirin#5041**

**closes #739 **

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [x] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [x] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [x] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [x] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [x] Related file selection: Only relevant files should be touched and no other files should be affected.
- [x] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [x] Clean commit history: The commits where the changes are made should be clear and organized.
- [x] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by cdagli** [comment]
If understood correct, we are going to put this KML on top of our map or? That would be awesome if possible ⭐

**Comment by cansirin** [comment]
Yes, we are going to put this KML on top of our map with the google maps icons etc. This still needs a couple changes before merging.

**Comment by cansirin** [comment]
Response coming from the endpoint `api/ahbap-locations`:
```
{
  "data": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          38.8079293,
          37.1705571,
          0
        ]
      },
      "properties": {
        "name": "Şanlıurfa - Levent Börek Haliliye",
        "description": "Ücretsi çay ve börek ikramı verilmektedir.",
        "styleUrl": "#icon-1577-7CB342",
        "icon-scale": 1,
        "icon": "images/icon-1.png"
      }
    },
    ...
  ]
}
```

**Comment by dopplerDistortion** [comment]
@cansirin #766 ile PR'ını güncelleyebilir misin ? Vercel deployment için

**Comment by cansirin** [comment]
I pulled the development branch and triggered the build again but it has failed again. I can look into this when I wake up

**Comment by eraygundogmus** [comment]
@fdemir check this out. he is @usirin brother and they worked together in this feature

**Pull request closed without merging**
