### PR TITLE
feat(677): add other platform links for mobile devices

### LINKED ISSUE #677: feat: add other platform links for mobile devices
## Define your request

** discord username: SynDrakes#8995

EN: The deprem.io & beniyiyim.com links show up on pc and tablets but not on mobile. They should be included on mobile UI too.

### PR DESCRIPTION
**Pull request by cenarturkmen**
# Description
I added visibility to links for mobiles, also moved translate button to top and fix the dropdown selection issue.

**discord username: yellowcloud#4988**

**closes #677**

image

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [x] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [x] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [x] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [x] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by eraygundogmus** [comment]
what about lang change selectbox? 


Screen Shot 2023-02-11 at 03 18 10

**Comment by cenarturkmen** [comment]
> what about lang change selectbox?
> 
> Screen Shot 2023-02-11 at 03 18 10

I moved to the top (under the notifications section)

**Review by oguzergul — DISMISSED** [review]

**Comment by oguzergul** [comment]
update: link is working now. LGTM

**Review by oguzergul — DISMISSED** [review]

**Review by serhhan — CHANGES_REQUESTED** [review]
That's cool, but I would like a UI/UX check before I proceed.

**Comment by CyhnYldz** [comment]
As we tested, the language selector is still at the bottom of the screen and also coverd by the timer and scan button.
@eraygundogmus @cenarturkmen 
Screen Shots:
Ekran görüntüsü 2023-02-11 121729
Ekran görüntüsü 2023-02-11 121802
Screenshot_20230211-122201_Chrome

**Comment by cdagli** [comment]
@cenarturkmen There has been some updates on the Figma please check if you can adapt your PR with those https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afetharita.com?node-id=2349%3A8093&t=meW4XvM6hFrhmaZG-0

**Comment by berkaydesign** [comment]
Design is done. You can check it out on Figma. @cenarturkmen 

image

**Comment by fdemir** [comment]
@cenarturkmen any updates?

**Comment by cenarturkmen** [comment]
I moved to the top-right but not to start on mobile
image

image

image

**Comment by fdemir** [comment]
no need to do that now

**Pull request closed without merging**
