### PR TITLE
fix: add selectAll clearAll button for filter component

### LINKED ISSUE #1108: bug: Need to add Select All or None to all Filters
## Bug Definition
As part of the original scope, we wanted to have Select All or None for the filter dropdown for better user engagement. 

-- Please add discord contact information
** discord username: @afetharita#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
## Describe how you are producing the bug step by step

1. Go to 'rc.afetharita.com.'
2. Click 'Hizmetler' 
3. Have an option as All or None from the downdown selections'

### PR DESCRIPTION
**Pull request by tolgakisin**
# Description
Added SelectAll-ClearAll button for filter component. "showSelectAll" parameter passed to component and it works only for multi-selection case.

**discord username: tolgakisin#1490 **

**closes #1108 **

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by MaksuCode** [comment]
When "Clear All" button is clicked the reason parameter is passed as empty string to the backend. In this case we receive over 1000 data. But as far as I understand we should not receive any since there is no reason selected.

I dont know how the filtering works on the backend API regarding the "reasons". Can you please help us here ? @eraygundogmus 

image

**Comment by eraygundogmus** [comment]
> 

I am not sure what happens when you pass an empty reason string on API side. 

But I am clear about that we don't need to send any parameter if we cleared all. 


To sum up: Payload below is enough
Screen Shot 2023-02-21 at 04 11 00

**Comment by MaksuCode** [comment]
@eraygundogmus We send the "reason" parameter as empty string. And this results in receiving every data.
So, I belive this is not sth we want when user clears every filter. 

This is how client-side sends the payload when user clears all the filters. 

image

**Comment by eraygundogmus** [comment]
@tolgakisin can you please update this PR?

**Comment by nazdezar** [comment]
Looks good, thank you!

**Comment by usirin** [comment]
Let's work with UI team first before introducing a new UI element. You can reopen this with a vetted fix by UI/UX team.

**Pull request closed without merging**
