### PR TITLE
fix: translation issues

### PR DESCRIPTION
**Pull request by el**
# Description

Fixes some translation issues and general cleanup

### CODE REVIEW

**Comment by eraygundogmus** [comment]
please open a new pr and include only related commits, I could merge this if there was only translation issues

**Comment by el** [comment]
@eraygundogmus What is unrelated about this pr? All the changes are related to the translation?

SCR-20230224-on1

**Comment by eraygundogmus** [comment]
> @eraygundogmus What is unrelated about this pr? All the changes are related to the translation?
> 
> SCR-20230224-on1

changes on the footer section is not related to translation, also changing the user interface

**Comment by el** [comment]
Ahh, let me revert that

**Comment by el** [comment]
> > @eraygundogmus What is unrelated about this pr? All the changes are related to the translation?
> > SCR-20230224-on1
> 
> changes on the footer section is not related to translation, also changing the user interface

Fixed the mobile issue. (I think my changes are related, so I didnt revert them)

**Comment by eraygundogmus** [comment]
> Member

oh. you are right.

**Pull request merged**
