### PR TITLE
fix(#796): Verified / unverified filter

### LINKED ISSUE #796: feat: Displaying verified and unverified data
Discord kanalımızda Merve Noyan ve diğer arkadaşların collect edip, yapay zeka ml gibi teknolojilerle otomasyon haline getirdiği datayı şu anlık güvensiz buluyoruz. 

The data collected and automated with ai, ml technologies by Merve Noyan and other friends are right now being unsecured.

Çünkü güçlü bir onay mekanızmasına giren datalar toplanıyor: Örnek: BabalaTV tek tek telefonla arıyor, AHBAP organizasyonu, vs vs. 

Because of the data is gathered with a strong confirmation mechanism. Example: BabalaTV is making phone calls one by one, Ahbap Organization etc.

Haritada initial ve default olarak, onaylanmış şeyleri göstermeliyiz. bir multiselect altında 
Under a multiselect; we have to display verified data by default and initial on the map.

https://mui.com/material-ui/react-select/
Verified: True
Unverified: False

### PR DESCRIPTION
**Pull request by cdagli**
# Description

**discord username: afetharita#0001**

**closes #796 **

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by cdagli** [comment]
This seems to be conflicted with https://github.com/acikkaynak/deprem-yardim-frontend/pull/819. 

#797 and #796 are very similar. Anyway, I'd still like to see the improvements in the page/index.ts one day on the main branch. Apart from that, most probably close this PR. 

Please feel free to take over this work if it is still valid. I won't be online for a while 👋

**Comment by usirin** [comment]
I was in the impression that `channels` and `visibility` filters are 2 different things. If this caused by me, or lack of communication, i am really sorry @cdagli that was not the intention at all.

I think there is still value in including an option to label a marker "verified" or "not verified" and i don't think these 2 features are conflicting with each other.

**Comment by sercanerhan** [comment]
As described in [the issue](https://github.com/acikkaynak/deprem-yardim-frontend/issues/796) the default value should be **Verified** cases. [Preview Link](https://deprem-yardim-frontend-git-fork-cdagli-feat-796-caner-afet.vercel.app/) opens with null selection.

The expectation is, on the initial default page load, only the **Verified** locations should be visible and  new multi-select filter should be selected as ** Verified**

**Comment by CyhnYldz** [comment]
As Test team we tested this PR. The main functionality is working as expected. Though, these are our findings FYI : 
1 - As sercan mentioned in his last comment the drop down comes with empty value and it should be "verified" as default
2 - (LOW prio) There is no localization of these filters. It is always in English
3 - (LOW prio) User must click somewhere else after selecting the filter so that client-side sends the request. 
4 - I dont know if it is the expected behaviour but currently there is no kind of flag which we can pass through backend to get the "verified" or "unverified" cases. "Babala" channel is considered as "verified" and "twitter" is not. That's why we pass a "channel" query param on the request url. Please confirm if this is going to be changed or not.
    Sample request : https://apigo.afetharita.com/feeds/areas?time_stamp=1675934179&ne_lat=36.31291199724548&ne_lng=36.35375976562501&sw_lat=36.05548306109947&sw_lng=35.9634017944336&channel=babala

**Pull request closed without merging**
