### PR TITLE
fix: help view translations

### LINKED ISSUE #1100: bug: English Translation problems
## Bug Definition
Some of the translations are forgotten

-- Please add discord contact information
** discord username: @afetharita#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to '.RC..'rc.afetharita.com
2. Bug appears

## Expected Behaviour
User manual to be english
Services filter reasons to be english

## Screen shots

Ekran görüntüsü 2023-02-21 015420

## Desktop Information
- Operating System: Windows 10
- Browser Chrome
- Version 110.0.5481.97 (Resmi Derleme) (64 bit) Sürümü

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

### PR DESCRIPTION
**Pull request by dopplerDistortion**
fixes: #1100

### CODE REVIEW

**Comment by eraygundogmus** [comment]
LGTM!

**Review by eraygundogmus — DISMISSED** [review]

**Comment by eraygundogmus** [comment]
Screen Shot 2023-02-21 at 03 25 44
is this expected? i felt like it should be bold or sth

**Comment by nazdezar** [comment]
@eraygundogmus @dopplerDistortion everything is translated to English as expected except the reasons from the filter dropdown are still in Turkish.

**Comment by eraygundogmus** [comment]
> @eraygundogmus @dopplerDistortion everything is translated to English as expected except the reasons from the filter dropdown are still in Turkish.

It is because get the data from backend. Please keep in touch with Hande about this subject and open an issue on backend repository.

**Comment by utkubenli** [comment]
https://prnt.sc/-bKagqWZYoL_ Also seeing the labels on the map details as not translated. Is this related?

**Comment by eraygundogmus** [comment]
> https://prnt.sc/-bKagqWZYoL_ Also seeing the labels on the map details as not translated. Is this related?

yes, we don't have multilanguage support on backend side yet

**Comment by utkubenli** [comment]
"Icerik detaylari" for some reason this is not translated. https://prnt.sc/KPKNXTujX2N5

**Comment by utkubenli** [comment]
Also SEVICES is written as SERVİCES

**Comment by utkubenli** [comment]
"Az Yogun" ......"Cok Yogun" legend from the manual is also in Turkish

**Comment by eraygundogmus** [comment]
@dopplerDistortion please can you fix the problems above?

**Comment by utkubenli** [comment]
Above issues resolved @dopplerDistortion Nice Job!

**Pull request merged**
