### PR TITLE
fix(#855): data sources popup fix

### PR DESCRIPTION
**Pull request by absolutezero13**
# Description
- The component for data sources popup was removed before, probably by mistake. It's added back and it is controlled by a state.

**discord username: afetharita#0001**

**closes #issue** #855

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by eraygundogmus — CHANGES_REQUESTED** [review]
please fix these:

* component naming: it is not banner
* fix UI issues, it does not work on mobile. 
- max width 700px as a breakpoint is not a good convention i think
- width %85 is not working properly because u already gave 24rem width on footer

**Comment by eraygundogmus** [comment]
also, let's ask for help from designers :) it left from old UI

**Comment by eraygundogmus** [comment]
@sercanerhan @handekaratas96

**Comment by sercanerhan** [comment]
addition to what @eraygundogmus mentioned, we have design files in [Figma](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=6370%3A32327&t=mM7YfRWtSjp5RSLe-4).

The component in this PR is visible close to the center of the app. According to the design files, it should appear on top of the `Scan Area` button.

**Comment by sercanerhan** [comment]
And yes, the bottom links are not visible in the mobile devices.
7F445135-A334-4B55-9905-C58525095BE8_1_102_o
we have discussed a similar issue with @oguzergul and he said that, he needs to work for an safe area definition for the mobile views.

**Comment by absolutezero13** [comment]
> addition to what @eraygundogmus mentioned, we have design files in [Figma](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=6370%3A32327&t=mM7YfRWtSjp5RSLe-4).
> 
> The component in this PR is visible close to the center of the app. According to the design files, it should appear on top of the `Scan Area` button.

will do

**Comment by absolutezero13** [comment]
> addition to what @eraygundogmus mentioned, we have design files in [Figma](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=6370%3A32327&t=mM7YfRWtSjp5RSLe-4).
> 
> The component in this PR is visible close to the center of the app. According to the design files, it should appear on top of the `Scan Area` button.

This component was completely removed from project and I retrieved it back, so the popup in this figma link is new design I believe? Also there is a text change as well, is that correct?

**Comment by eraygundogmus** [comment]
Yas, indeed 

> > addition to what @eraygundogmus mentioned, we have design files in [Figma](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=6370%3A32327&t=mM7YfRWtSjp5RSLe-4).
> 
> > 
> 
> > The component in this PR is visible close to the center of the app. According to the design files, it should appear on top of the `Scan Area` button.
> 
> 
> 
> This component was completely removed from project and I retrieved it back, so the popup in this figma link is new design I believe? Also there is a text change as well, is that correct?

**Comment by absolutezero13** [comment]
@eraygundogmus @sercanerhan 
I've updated the PR, additionally I fixed the bottom links issue, they are visible on mobile phones now. Could you check?

**Comment by eraygundogmus** [comment]
> @eraygundogmus @sercanerhan I've updated the PR, additionally I fixed the bottom links issue, they are visible on mobile phones now. Could you check?

Hi, it seems nice, thanks!

Please can you check these? 

1.  There is no title in vercel preview link as designed in Figma, also close button is seems larger Screen Shot 2023-02-28 at 21 48 00
2. We can set a constant for height and make this area scrollable, because text can be longer in other languages or it can stuck on some devices
Screen Shot 2023-02-28 at 21 48 55

**Comment by absolutezero13** [comment]
@eraygundogmus text is also different than figma, @sercanerhan said it should be the old text, not on figma version. I'm not sure which one is correct.

I'll make adjustments for height.

**Pull request merged**
