### PR TITLE
fix(#695): Partially resolves issues pertaining to the the BU ALANI TARA (scan this area) button.

### LINKED ISSUE #695: bug/refactor: `BU ALANI TARA` (scan this area) button does not trigger a request
## Bug Definition

The `BU ALANI TARA` (scan this area) button is not triggering a request. In the same vein, no request is performed after the countdown hits zero.

-- Please add discord contact information
** discord username: namcojoulder#1062**

## Bug environment
Describe the environment produces the bug. For example: rc.afetharita.com and/or afetharita.com
rc.afetharita.com

## Describe how you are producing the bug step by step
1. Navigate to rc.afetharita.com
3. Click the `BU ALANI TARA` (SCAN THIS AREA) button (top & center of the screen)
4. No request is made to the `/areas` endpoint

## Expected behavior
Even if the response is the same as the last one, a request must be made when the `BU ALANI TARA` (SCAN THIS AREA) button is clicked.

P.S: This might be expected behavior. (In theory, unless the REST GET URL changes, the same response will be returned, thus no benefit in making another request) In that case, it might make sense to remove the countdown completely, since we won't make a request when the countdown hits zero and the whole thing might become redundant.

## Screen shots
If applicable, add screen shots to elaborate the issue.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
If we are sure that the response will be the same when unless the URL changes, the countdown becomes redundant. If the explained behavior is expected behavior, removing the countdown may be considered. Or this issue can be closed.

Thanks.

### PR DESCRIPTION
**Pull request by efegurkan**
# Description

**discord username: namcojoulder#1062**

**closes #695**

Partially resolves issues pertaining to the the `BU ALANI TARA` (scan this area) button.

Fixes: 
- The button *does not* make a request to BE unless the map is panned beforehand.
- The button *does make a request to BE _after_ the map is panned.

## Things to check before creating a PR
- [X] I have inspected my topic, checked.
- [X] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by emr3rden** [comment]
TR: PR'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu PR'ı ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "PR" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "PR" in English. Could you please edit it in english?

https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/PULL_REQUEST_TEMPLATE.md

**Review by serhhan — APPROVED** [review]
Solves the problem, but what you mean by "partially"? It would be helpful if we added other parts to the issue to make it easier to follow.

**Comment by sevilayerkan** [comment]
As a test team we had checked this pr in the first 10 second period it sends requests but after that we could not get the request as expected @eraygundogmus

**Comment by usirin** [comment]
Closing it, please reopen after test criteria is met.

**Pull request closed without merging**
