### PR TITLE
feat: add depremio data request

### LINKED ISSUE #1161: data-request: depremio
### discord username

Luuwa#0220

### channel name

depremio

### reasons

Twitter verisi gibi çoklu

### icon

tanım yok

### extra_parameters example

_No response_

### PR DESCRIPTION
**Pull request by eraygundogmus**
closes #1161

### CODE REVIEW

**Comment by nazdezar** [comment]
@eraygundogmus I couldn't find deprem.io data in the dev branch. Do you have examples or locations that I can focus? Do we have data in the dev branch from this channel?

**Comment by eraygundogmus** [comment]
> @eraygundogmus I couldn't find deprem.io data in the dev branch. Do you have examples or locations that I can focus? Do we have data in the dev branch from this channel?

can we be sure about "depremio"? is it the right channel name?

**Comment by sercanerhan** [comment]
it is `depremio` and returns 3 results.
image

**Comment by sercanerhan** [comment]
I can see the marker on the above preview link's [Gaziantep location](https://deprem-yardim-frontend-git-data-request-1161-afet.vercel.app/en?lat=37.083114700538744&lng=37.37011849880219&zoom=18&reasons=kurtarma%2Cbarinma%2Celektronik%2Csaglik%2Cyemek%2Csu%2Cgiysi%2Clojistik%2Cenkaz%2Cgenel%2Cyardim%2Cguvenli-noktalar%2Chayvanlar-icin-tedavi%2Ckonaklama%2Cerzak&id=1601379)
image

**Pull request merged**
