### PR TITLE
Map rerender

### PR DESCRIPTION
**Pull request by hamitaksln**
We have state in Home component so whenever a value changed, it re-renders. For example on toggleDrawer, it close opened cluster, it's because we re-render and loses its state.

### CODE REVIEW

**Comment by eraygundogmus** [comment]
@hamitaksln can you resolve conflicts?

**Comment by hamitaksln** [comment]
@eraygundogmus Sure

**Comment by eraygundogmus** [comment]
@hamitaksln can you open a pr for readme.md? we need turkish docs to at least refer to state management repository

**Comment by hamitaksln** [comment]
@eraygundogmus Sure I will do that.

**Pull request merged**
